CREATE DATABASE IF NOT EXISTS CAPSTONE_ECOMMERCE_DB;

USE DATABASE CAPSTONE_ECOMMERCE_DB;

CREATE SCHEMA IF NOT EXISTS RAW;


CREATE OR REPLACE TABLE RAW.PRODUCTS (
    ID INTEGER,
    TITLE STRING,
    PRICE FLOAT,
    DESCRIPTION STRING,
    CATEGORY STRING,
    IMAGE STRING,
    RATING_RATE FLOAT,
    RATING_COUNT INTEGER
);

SHOW TABLES IN SCHEMA RAW;

SELECT COUNT(*)
FROM RAW.PRODUCTS;

SELECT *
FROM RAW.PRODUCTS
LIMIT 10;

CREATE SCHEMA IF NOT EXISTS ANALYTICS;

SELECT *
FROM ANALYTICS.STG_PRODUCTS
LIMIT 10;

SELECT
    title,
    category,
    price,
    price_segment,
    rating_rate,
    rating_category,
    review_volume,
    price_band
FROM ANALYTICS.INT_PRODUCTS
LIMIT 10;

SELECT * FROM ANALYTICS.GOLD_CATEGORY_SUMMARY;

SELECT * FROM ANALYTICS.GOLD_PRODUCT_RATINGS;

SELECT * FROM ANALYTICS.GOLD_PRICE_SEGMENTS;

