name: Data Pipeline CI

on:
  push:
    branches:
      - main
      - master

  pull_request:
    branches:
      - main
      - master

jobs:

  validate:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Python Packages
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas snowflake-connector-python python-dotenv

      - name: Verify Python Scripts
        run: |
          python -m py_compile scripts/extract.py
          python -m py_compile scripts/load_snowflake.py

      - name: Install dbt
        run: |
          pip install dbt-core dbt-snowflake

      - name: Verify dbt Installation
        run: dbt --version